language: python
python:
  - "3.8"

# The pipeline requires GNU parallel; Python retry and requests modules; and bcftools.
before_install:
  - sudo apt-get -y install parallel
install:
  - pip -q install retry requests
  - git clone -q git://github.com/samtools/htslib.git
  - git clone -q git://github.com/samtools/bcftools.git
  - cd bcftools && make --quiet --jobs `nproc` && cd ..
  - export PATH=$PATH:bcftools

# For the actual test, we're running a set of 2,000 ClinVar variants through VEP and comparing the result with the
# expected one (diff will exit with return code 0 if the files are identical, and with 1 otherwise). Of course, this
# means that when VEP updates, the test will break; however, this is exactly the intention, as in this case we will be
# able to compare the results and see if they make sense.
script:
  - ls
  - bash vep_mapping_pipeline/run_consequence_mapping.sh test/input.vcf output_mappings.tsv
  - diff test/output_mappings.tsv output_mappings.tsv
