dist: bionic
language: python
python:
  - "3.8"

install:
  - echo 'Installing main pipeline dependencies'
  - pip3 install -r requirements.txt
  - pip3 install coveralls
  - python setup.py install

  - echo 'Installing VEP and repeat expansion pipeline dependencies'
  - sudo apt update
  - sudo apt -y install samtools bcftools parallel libbz2-dev liblzma-dev
  - pip3 -q install -r vep-mapping-pipeline/requirements.txt

script:
  - echo 'Test 1. Main pipeline'
  - python3 setup.py test
  - cd clinvar-xml-parser && mvn clean test jacoco:report coveralls:report && cd -

  # VEP / repeat expansion pipeline tests.
  # For the actual test, we're running a set of 2,000 ClinVar variants through VEP and comparing the result with the
  # expected one (diff will exit with return code 0 if the files are identical, and with 1 otherwise). Of course, this
  # means that when VEP updates, the test will break; however, this is exactly the intention, as in this case we will be
  # able to compare the results and see if they make sense.
  - echo 'Test 2. VEP mapping pipeline'
  - cd vep-mapping-pipeline
  - bash run_consequence_mapping.sh vep_mapping_pipeline/test/input.vcf output_mappings.tsv
  - diff vep_mapping_pipeline/test/output_mappings.tsv output_mappings.tsv

  - echo 'Test 3. Repeat expansion pipeline'
  - pip3 install --editable .
  - pytest
  - cd ..

after_success:
  - coveralls --merge=clinvar-xml-parser/target/coveralls.json
