language: python
python:
  - "3.5"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - python setup.py install
# command to run tests
script:
  - python3 setup.py test
  - cd clinvar-xml-parser && mvn clean test jacoco:report coveralls:report && cd -
after_success:
  - coveralls --merge=clinvar-xml-parser/target/coveralls.json
