# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: EVA Open Targets pipelines

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install native packages
      run: |
        sudo apt update
        sudo apt -y install samtools bcftools parallel libbz2-dev liblzma-dev
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test 1. Main pipeline and repeat expansion pipeline
      run: |
        python setup.py install
        python -m pytest --cov=eva_cttv_pipeline --cov=consequence_prediction tests

    - name: Test 2. VEP mapping pipeline
      run: |
        bash tests/consequence_prediction/vep_mapping_pipeline/test_vep_pipeline.sh
    
    - name: Upload the coverage data to Coveralls
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        coveralls
